### ISSUE TITLE
Firewall rules

### ISSUE THREAD

**Issue by sp1ritCS** [sireliah/dragit#9]
Is it possible for dragit to automatically punch holes into firewalld, if it has to listen to a specific port?

I know that gnome-network-displays are doing something like this, might be a good idea to look at them and how they do it.

**Comment by sireliah** [comment]
It's great idea, I'll research that!

**Comment by sireliah** [comment]
It seems that gnome-network-displays adds new firewalld zone automatically:

https://gitlab.gnome.org/GNOME/gnome-network-displays/-/issues/134
https://gitlab.gnome.org/GNOME/gnome-network-displays/-/commit/c2a81a501ec1eb231c05dd47416fe935d6573c13

**Comment by sp1ritCS** [comment]
But they are changing to that new zone at runtime if it isn't enabled.
https://gitlab.gnome.org/GNOME/gnome-network-displays/-/commit/fed0e1311e89f229cc683abb5c3f9a996fbeb0a3

**Comment by sireliah** [comment]
Yeah, I see what they are doing there. They indeed expect the zone to be there and in case it is not, they create it. It seems that they operate on [fixed port](https://gitlab.gnome.org/GNOME/gnome-network-displays/-/blob/master/src/nd-firewalld.c#L132).

The interface they use to communicate with the firewalld is D-Bus. We could do the same, since there are pretty good D-Bus bindings for Rust, however there are is a gotcha here:

- Talking to firewalld requires elevated privileges from the user. That is, user will be prompted for a password in case there is a zone config that doesn't allow Dragit to work (I think this is implied by `G_DBUS_CALL_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION` flag. We should be smart here and prompt user only if this is absolutely necessary, so when there are rules that would block libp2p or mdns traffic. 
- We should clearly explain why Dragit demands those privileges and what it will do to the user's computer.
- In context of Flatpak application - maybe it's not an issue, but using D-Bus to change settings of the host system is yet another hole in the sandbox. [Docs don't say it's bad](https://docs.flatpak.org/en/latest/conventions.html?highlight=d-bus#d-bus), but you know.

Having said that, I'll run some tests with my local firewalld and see if there are any potential problems.

**Comment by sp1ritCS** [comment]
> there are pretty good D-Bus bindings for Rust

if you're talking about zbus, absolutely. dbus-rs not so much :D



> We should clearly explain why Dragit demands those privileges and what it will do to the user's computer.

well, if I remember correctly, gnome-network-displays shows a similar polkit authentication dialog as firewall-config itself:
![image](https://user-images.githubusercontent.com/31540351/119271892-da666700-bc03-11eb-8b04-a6792778d59a.png)
I think it should be fairly obvious with that message that dragit needs to modify the firewall zone.

> In context of Flatpak application - maybe it's not an issue, but using D-Bus to change settings of the host system is yet another hole in the sandbox. Docs don't say it's bad, but you know

well, I guess it's better than not working at all
¯\\\_(ツ)_/¯

**Comment by sireliah** [comment]
@sp1ritCS I'm not quite done with the code yet, but it would be great if you could take a look at [this PR and particularly firewall module](https://github.com/sireliah/dragit/pull/12/files#diff-312a478f365b83d39739b01a927a72d77ae697affb3b85f3bbaa720a660ba8bd). I implemented adding mdns service and fixed Dragit port in case it's not available in runtime config.

**Comment by sireliah** [comment]
Closing the issue. The next release (including Flatpak) will contain the change!

**Comment by nekohayo** [comment]
Potential follow-up idea in issue #32, in case @sp1ritCS is interested.
